crs/urls.py
from django.urls import path

from labs.views import get_labs_page, get_labs_dashboard_page, get_labs_highmap_json, \
    get_district_count_labs_report_json, get_laboratory_wise_report_count, get_labs_reports_json, get_reports_no_param

urlpatterns = [
    path('crs_page/', get_labs_page, name='crs_page'),
]

pac/urls.py
from django.urls import path

from pac.views import pac_login_page, pac_signup_page, pac_add_activity, pac_page, pac_view_activity, \
    get_activity_photos, download_certificate

urlpatterns = [
    path('', pac_page, name='pac_page'),
    path('pac_add_activity', pac_add_activity, name='pac_add_activity'),
    path('pac_view_activity', pac_view_activity, name='pac_view_activity'),
    path('pac_login/', pac_login_page, name='pac_login_page'),
    path('pac_signup/', pac_signup_page, name='pac_signup_page'),
    path('get_act_photos/', get_activity_photos, name='get_act_photos'),
    path('download_certificate/<certificate>/', download_certificate, name='download_certificate'),

    # path('upload/', views.upload_activity, name='upload_activity'),
]

spiu/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from fire_points.views import get_fire_points, get_fp_page
from spiu import settings
from spiu.views import homepage, signup, disclaimer_page, spiu_page, dashboard_page, reset_password_spiu, redirect_ippi, \
    redirect_ippi_soe

urlpatterns = [
                  # path('grappelli/', include('grappelli.urls')),  # grappelli URLS
                  path('admin/', include("django_admin_kubi.urls")),
                  path('admin/', admin.site.urls),
                  path('^', include('django.contrib.auth.urls')),
                  path('disclaimer/', disclaimer_page, name='disclaimer'),
                  path('dashboard/', dashboard_page, name='dashboard'),
                  path('home/', homepage, name='home'),
                  path('gis/', include('spiu_gis.urls')),
                  path('signup/', signup, name='signup'),
                  path('', spiu_page, name='spiu'),
                  path('spiu/', spiu_page, name='spiu'),
                  path('labs/', include('labs.urls')),
                  path('pac/', include('pac.urls')),
                  path('ioed/', include('giz.urls')),
                  path('wwtp/', include('wwtp.urls')),
                  path('fire_points/', get_fire_points, name='fire_points'),
                  path('fp/', get_fp_page, name='fp'),
                  path('reset_password/', reset_password_spiu, name='reset_password'),
                  path('ippi/', redirect_ippi, name='ippi'),
                  path('ippi/soe23/', redirect_ippi_soe, name='soe23'),
                  path('imar/', include('imar.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pac/models.py
from django.contrib.auth.models import User
from django.db import models

from spiu_gis.models import TblDistricts


class Activity(models.Model):
    district = models.ForeignKey(TblDistricts, on_delete=models.CASCADE, db_column='district_id', blank=True, null=True,
                                 verbose_name="District")
    activity_name = models.CharField(max_length=255)
    activity_address = models.TextField()
    activity_remarks = models.TextField(blank=True, null=True)
    latitude = models.FloatField()
    longitude = models.FloatField()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, db_column='created_by', blank=True, null=True)
    updated_by = models.IntegerField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)


class Photo(models.Model):
    image = models.ImageField(upload_to='activity_photos/')
    image_name = models.CharField(max_length=255, blank=True, null=True)
    activities = models.ForeignKey(Activity, on_delete=models.CASCADE, blank=True, null=True)


class PacCertificates(models.Model):
    first_name = models.CharField(max_length=255, blank=True, null=True)
    district = models.CharField(max_length=255, blank=True, null=True)
    organization_name = models.CharField(max_length=255, blank=True, null=True)
    count = models.IntegerField(blank=True, null=True)
    remarks = models.CharField(max_length=255, blank=True, null=True)
    reg_download = models.BooleanField(blank=True, null=True)
    award_download = models.BooleanField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'pac_certificates'

pac/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from spiu.models import GENDER_CHOICES
from spiu_gis.models import TblDistricts
from .models import Activity, Photo


class SignupForm(UserCreationForm):
    mobile_no = forms.IntegerField(required=False, label="Mobile No")
    email = forms.EmailField(max_length=200, help_text='Required')
    district_id = forms.ModelChoiceField(label='District Name',
                                         queryset=TblDistricts.objects.all().order_by('district_name'))
    organization_name = forms.CharField(required=True, max_length=250, label="Organization Name")
    gender = forms.CharField(
        max_length=100,
        required=False,  # You can set this to True if the field is mandatory
        widget=forms.Select(choices=GENDER_CHOICES),
        # Add any other relevant attributes like blank, null, etc.
    )

    class Meta:
        model = User
        fields = (
            'first_name', 'username', 'district_id', 'gender', 'mobile_no', 'email', 'organization_name', 'password1',
            'password2')
        labels = {'mobile_no': 'Mobile Number', }


class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True


class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result


class ActivityPhotoForm(forms.ModelForm):
    district = forms.ModelChoiceField(
        queryset=TblDistricts.objects.all().order_by('district_name'),
        empty_label="Select a District",
        widget=forms.Select(attrs={'class': 'form-select'})
    )
    images = MultipleFileField(label='Select files', required=False)

    class Meta:
        model = Activity
        fields = ['district', 'activity_name', 'activity_address', 'activity_remarks', 'latitude', 'longitude',
                  'images']

    def save(self, commit=True, request=None):
        activity = super().save(commit=False)
        images = self.files.getlist('images')

        if request:
            user = request.user
            if user.is_authenticated:
                activity.created_by = user

        if commit:
            activity.save()

        # Create a new Photo instance for each uploaded image
        if images:
            for image in images:
                Photo.objects.create(activities=activity, image=image)

        return activity

pac/views.py
import json
import os

from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse, JsonResponse, FileResponse
from django.shortcuts import render
from django.template import loader

from spiu.settings import MEDIA_ROOT
from spiu.utils import date_handler, date_format_handler
from spiu_gis.models import TblDistricts
from .models import Photo, Activity, PacCertificates


# Create your views here.
def get_pac_page(request):
    template = loader.get_template('pac_index.html')
    return HttpResponse(template.render({}, request))


from django.shortcuts import render, redirect
from .forms import ActivityPhotoForm, SignupForm


def pac_login_page(request):
    user_name = request.POST.get('username')
    password = request.POST.get('password')
    next_url = request.GET.get('next', '/pac')
    try:
        user = authenticate(username=user_name, password=password)
        login(request, user)
        return redirect(next_url)
    except Exception as e:
        print(e.args)
    return render(request, 'pac_login.html', {})


def pac_signup_page(request):
    if request.method == 'POST':
        data = request.POST
        post_data_copy = request.POST.copy()
        post_data_copy['username'] = data['email']
        post_data_copy['password2'] = data['password1']
        form = SignupForm(post_data_copy)
        if form.is_valid():
            user = form.save()
            user.profile.mobile_no = form.cleaned_data.get('mobile_no')
            user.profile.email = form.cleaned_data.get('email')
            district_id = form.cleaned_data.get('district_id')
            user.profile.district_id = district_id
            user.profile.district = district_id.district_name
            user.profile.gender = form.cleaned_data.get('gender')
            user.profile.organization_name = form.cleaned_data.get('organization_name')
            user.save()
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('/pac')  # Redirect to the home page after signup
    else:
        form = SignupForm()
    return render(request, 'pac_register.html', {'form': form})


def pac_add_activity(request):
    if request.method == 'POST':
        form = ActivityPhotoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save(commit=False, request=request)  # Get the Activity instance without saving to the database
            messages.success(request, 'Activity uploaded successfully.')
        else:
            messages.error(request, form.errors)
    else:
        form = ActivityPhotoForm()
    return render(request, 'pac_add_activity.html', {'form': form})


def pac_page(request):
    reg_users = User.objects.filter(id__gt=95).count()
    act_count = Activity.objects.all().count()
    return render(request, 'pac_index.html', {'reg_users': reg_users, 'activities_count': act_count})


def pac_view_activity(request):
    if request.user.is_superuser or request.user.id == 192:
        activities = Activity.objects.all()
    else:
        activities = Activity.objects.filter(created_by=request.user.id)
    data = list(
        activities.values('id', 'district__district_name', 'activity_name', 'activity_address', 'latitude', 'longitude',
                          'created_at', 'created_by__username'))
    data = json.dumps(data, default=date_format_handler)
    return render(request, 'pac_view_activities.html', {'data': data})


def get_activity_photos(request):
    activity_id = request.GET.get('activity_id')

    # Assuming you have a Photo model with a ForeignKey to Activity
    photos = Photo.objects.filter(activities=activity_id)

    # Assuming the Photo model has an 'image' field to store image URLs
    photo_data = [{'image_url': photo.image.url} for photo in photos]

    return JsonResponse(photo_data, safe=False)


@login_required
def download_certificate(request, certificate):
    try:
        user_id = request.user.id
        certificate_instance = PacCertificates.objects.filter(pk=user_id)
        if certificate_instance.count() == 0:
            return HttpResponse(
                "Message: You are not registered with this campaign",
                status=500)
        else:
            certificate_instance = PacCertificates.objects.get(pk=user_id)
        # file_name = '1.png'
        file_name = str(user_id) + '.pdf'
        if certificate and certificate == 'a':
            url = MEDIA_ROOT + '/pac/certificates/awards/' + file_name
            certificate_instance.award_download = True
        else:
            url = MEDIA_ROOT + '/pac/certificates/registration/' + file_name
            certificate_instance.reg_download = True
        # content_type = get_content_type(file_name)
        response = FileResponse(open(url, 'rb'), content_type='application/pdf')
        response["Access-Control-Allow-Origin"] = "*"
        response["Access-Control-Allow-Methods"] = "GET, OPTIONS"
        response["Access-Control-Max-Age"] = "1000"
        response["Access-Control-Allow-Headers"] = "X-Requested-With, Content-Type"
        response['X-Frame-Options'] = 'ALLOWALL'
        # response['Content-Security-Policy'] = "frame-ancestors 'self' http://localhost:86"
        # response["Content-Disposition"] = "filename={}".format(file_name)
        response["Content-Disposition"] = "attachment; filename={}".format(file_name)
        certificate_instance.save()
        return response
    except Exception as e:
        return HttpResponse(
            "Award certificate is only issued to those who conducted activities in schools, For any query please contact at 0333-6862840 or email at adgis@epd.punjab.gov.pk ",
            status=500)


def get_content_type(file_name):
    file_extension = os.path.splitext(file_name)[1].lower()
    content_type = ""
    if file_extension == '.pdf':
        content_type = "application/pdf"
    elif file_extension == '.png':
        content_type = "image/png"
    elif file_extension == '.jpg' or file_extension == '.jpeg':
        content_type = "image/jpeg"
    else:
        # Handle unsupported file types or provide a default content type
        content_type = "application/octet-stream"
    return content_type

pac/templates/base_pac.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <link href="{% static "external/bootstrap-5.1.3/css/bootstrap.min.css" %}" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% block extra_styles %}
    {% endblock %}
    <script src="{% static "external/jquery/jquery-3.3.1.min.js" %}"></script>
    <script src="{% static "external/bootstrap-5.1.3/js/bootstrap.bundle.min.js" %}"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    {% block extra_scripts %}
    {% endblock %}
</head>
<body >
{% include "includes/navbar_pac.html" %}
<main class="container-fluid" >
    {% block main_content %}
    {% endblock %}
</main>
{% block footer %}
    {% include "includes/footer.html" %}
{% endblock %}
</body>
</html>

pac/templates/pac_add_activity.html
{% extends 'base_pac.html' %}
{% load static %}
{% block extra_scripts %}
    <script src="https://cdn.jsdelivr.net/npm/ol@v8.1.0/dist/ol.js"></script>
    <script src="{% static "assets/js/geo_location.js" %}"></script>

{% endblock %}
{% block extra_styles %}
    <link href="{% static "assets/css/pac_main.css" %}" rel="stylesheet">
    <style>

    </style>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/ol@v8.1.0/ol.css">
{% endblock %}
{% block title %}Home{% endblock %}
{% block main_content %}
    <div class="container" style="margin-top: 100px">
        <div class="row ">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <label for="track">
                            If not at current location,than please click on your exact location on map
                        </label>
                    </div>
                    <div id="map" class="card-body"></div>
                </div>
            </div>
            <div class="col-md-6">
                <form method="post" action="{% url 'pac_add_activity' %}" class="row g-3" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="col-md-12">
                        <label for="{{ form.district.id_for_label }}" class="form-label">District</label>
                        {{ form.district }}
                    </div>
                    <div class="col-12">
                        <label for="{{ form.activity_name.id_for_label }}" class="form-label">Activity Location
                            Name</label>
                        <input type="text" class="form-control" id="{{ form.activity_name.id_for_label }}"
                               name="{{ form.activity_name.name }}"
                               placeholder="Name of School or Place where you are visiting" required>
                    </div>
                    <div class="col-12">
                        <label for="{{ form.activity_address.id_for_label }}" class="form-label">Activity Location
                            Address</label>
                        <textarea class="form-control" id="{{ form.activity_address.id_for_label }}"
                                  name="{{ form.activity_address.name }}" rows="3"
                                  placeholder="Chak/Village/Town Name,Road Name, Tehsil, Post office, other place mark"
                                  required></textarea>
                    </div>

                    <div class="col-md-6">
                        <label for="{{ form.latitude.id_for_label }}" class="form-label">Latitude</label>
                        <input type="number" step="any" class="form-control" id="{{ form.latitude.id_for_label }}"
                               name="{{ form.latitude.name }}" value="{{ form.latitude.value }}">
                    </div>

                    <div class="col-md-6">
                        <label for="{{ form.longitude.id_for_label }}" class="form-label">Longitude</label>
                        <input type="number" step="any" class="form-control" id="{{ form.longitude.id_for_label }}"
                               name="{{ form.longitude.name }}" value="{{ form.longitude.value }}">
                    </div>
                    <div class="col-12">
                        <label for="id_images" class="form-label">Attach Photos</label>
                        <input class="form-control" type="file" id="id_images"
                               accept="image/*" name="images" multiple required>
                        <span class="help-block">Choose one or more images from directory and than click on upload button</span>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <div class="preview-container" id="image-preview-container"></div>
                        </div>
                        <!-- <button type="button" id="add-more-images" class="btn btn-primary">Add Image</button> -->
                    </div>

                    {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    <div class="col-12 text-center">
                        <button type="submit" class="btn btn-primary">Upload Data</button>
                    </div>
                </form>
                <div class="row" style="margin-top: 50px !important;"></div>
            </div>
        </div>
    </div>
{% endblock %}

pac/templates/pac_register.html
{% extends 'base_pac.html' %}
{% load static %}
{% block extra_scripts %}
{% endblock %}
{% block extra_styles %}
{% endblock %}
{% block title %}Home{% endblock %}
{% block main_content %}
    <style>
        .login_form {
            margin-top: 15vh;
            padding: 20px 22px;
            background: #f1e7cb !important
        }

        .helptext {
            color: #000505;
            font-size: small;
        }

        .errorlist {
            color: red;
        }
    </style>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <form class="login_form" method="post" action="">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="first_name" class="form-label">Name:</label>
                                <input type="text" class="form-control" id="first_name" placeholder="Enter your Name"
                                       name="first_name" required>
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="id_gender" class="form-label">Gender:</label>
                                <select class="form-control form-select" name="gender" placeholder="Select your gender"
                                        id="id_gender">
                                    <option value="" selected>---------</option>
                                    <option value="male">Male</option>
                                    <option value="female">Female</option>
                                    <option value="-">Rather not say</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="id_district_id" class="form-label">District Name:</label>
                                <select class="form-control form-select" name="district_id"
                                        id="id_district_id">
                                    <option value="" selected>---------</option>

                                    <option value="29">Attock</option>

                                    <option value="3">Bahawalnagar</option>

                                    <option value="2">Bahawalpur</option>

                                    <option value="36">Bhakkar</option>

                                    <option value="28">Chakwal</option>

                                    <option value="11">Chiniot</option>

                                    <option value="7">Dera Ghazi Khan</option>

                                    <option value="10">Faisalabad</option>

                                    <option value="17">Gujranwala</option>

                                    <option value="16">Gujrat</option>

                                    <option value="15">Hafizabad</option>

                                    <option value="9">Jhang</option>

                                    <option value="27">Jhelum</option>

                                    <option value="21">Kasur</option>

                                    <option value="25">Khanewal</option>

                                    <option value="35">Khushab</option>

                                    <option value="20">Lahore</option>

                                    <option value="6">Layyah</option>

                                    <option value="24">Lodhran</option>

                                    <option value="14">Mandi Bahauddin</option>

                                    <option value="34">Mianwali</option>

                                    <option value="23">Multan</option>

                                    <option value="5">Muzaffargarh</option>

                                    <option value="19">Nankana Sahib</option>

                                    <option value="13">Narowal</option>

                                    <option value="32">Okara</option>

                                    <option value="31">Pakpattan</option>

                                    <option value="1">Rahim Yar Khan</option>

                                    <option value="4">Rajanpur</option>

                                    <option value="26">Rawalpindi</option>

                                    <option value="30">Sahiwal</option>

                                    <option value="33">Sargodha</option>

                                    <option value="18">Sheikhupura</option>

                                    <option value="12">Sialkot</option>

                                    <option value="8">Toba Tek Singh</option>

                                    <option value="22">Vehari</option>

                                </select>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="organization_name" class="form-label">Organization Name:</label>
                                <input type="text" class="form-control" id="organization_name"
                                       placeholder="Organization or University Name"
                                       name="organization_name" required>
                            </div>
                        </div>
                    </div>
                    <!--
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="username" class="form-label">User Name:</label>
                                    <input type="text" class="form-control" id="username" placeholder="Enter username"
                                           name="username">
                                    <span class="helptext help-block">Username required Letters, digits and @/./+/-/_ only.</span>
                                </div>
                            </div>
                        </div>
                      -->
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="email" class="form-label">Email:</label>
                                <input type="email" class="form-control" id="email" placeholder="Enter Email"
                                       name="email" required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="mobile_no" class="form-label">Mobile No:</label>
                                <input type="number" class="form-control" id="mobile_no"
                                       placeholder="Enter Mobile No (03001234567)"
                                       name="mobile_no" required>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="password1" class="form-label">Password:</label>
                                <input type="password" class="form-control" id="password1" placeholder="Enter password"
                                       name="password1">
                                <span class="helptext">
                                    <ul>
                                    <li>Your password must contain at least 8 characters.</li>
                                    <li>Your password can’t be entirely numeric.</li>
                                </ul>
                                </span>

                            </div>
                        </div>
                    </div>
                    <!--
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="password2" class="form-label">Password Confirmation:</label>
                                    <input type="password" class="form-control" id="password2" placeholder="Enter password"
                                           name="password2">
                                    <span class="helptext">Enter the same password as before, for verification.</span>
                                </div>
                            </div>
                        </div>
                    -->
                    {% if form.errors %}
                        <p style="color: red">{{ form.errors }}</p>
                    {% endif %}
                    <div class="row" style="margin-top: 10px">
                        <div class="col-md-12">
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary col-md-12">Sign Up</button>
                            </div>
                        </div>
                    </div>
                    <input type="hidden" name="next" value="{{ next }}"/>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="col-md-12">
                                    <a style="color: #0a53be" href="/pac/pac_login">if already registered, please
                                        login?</a>
                                </label>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
{% endblock %}